# This workflow runs every Saturday @ 1900 UTC (NOON PST)
name: i18n download bot
on:
  schedule:
    - cron: "0 19 * * 6"
    - cron: "30 23 * * 6"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DIM
        uses: actions/checkout@v2

      - name: Download updated i18n files
        uses: crowdin/github-action@1.0.4
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          create_pull_request: false
          push_translations: false
          source: src/locale/dim.json
          translation: src/locale/%android_code%/dim.json
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: sort all dim.json
        run: |
          jq -S . src/locale/dim.json > src/locale/dim_sorted.json && mv src/locale/dim_sorted.json src/locale/dim.json
          jq -S . src/locale/de/dim.json > src/locale/de/dim_sorted.json && mv src/locale/de/dim_sorted.json src/locale/de/dim.json
          jq -S . src/locale/es/dim.json > src/locale/es/dim_sorted.json && mv src/locale/es/dim_sorted.json src/locale/es/dim.json
          jq -S . src/locale/es-mx/dim.json > src/locale/es-mx/dim_sorted.json && mv src/locale/es-mx/dim_sorted.json src/locale/es-mx/dim.json
          jq -S . src/locale/fr/dim.json > src/locale/fr/dim_sorted.json && mv src/locale/fr/dim_sorted.json src/locale/fr/dim.json
          jq -S . src/locale/it/dim.json > src/locale/it/dim_sorted.json && mv src/locale/it/dim_sorted.json src/locale/it/dim.json
          jq -S . src/locale/ja/dim.json > src/locale/ja/dim_sorted.json && mv src/locale/ja/dim_sorted.json src/locale/ja/dim.json
          jq -S . src/locale/ko/dim.json > src/locale/ko/dim_sorted.json && mv src/locale/ko/dim_sorted.json src/locale/ko/dim.json
          jq -S . src/locale/pl/dim.json > src/locale/pl/dim_sorted.json && mv src/locale/pl/dim_sorted.json src/locale/pl/dim.json
          jq -S . src/locale/pt-br/dim.json > src/locale/pt-br/dim_sorted.json && mv src/pt-br/locale/dim_sorted.json src/locale/pt-br/dim.json
          jq -S . src/locale/ru/dim.json > src/locale/ru/dim_sorted.json && mv src/locale/ru/dim_sorted.json src/locale/ru/dim.json
          jq -S . src/locale/zh-chs/dim.json > src/locale/zh-chs/dim_sorted.json && mv src/locale/zh-chs/dim_sorted.json src/zh-chs/locale/dim.json
          jq -S . src/locale/zh-cht/dim.json > src/locale/zh-cht/dim_sorted.json && mv src/locale/zh-cht/dim_sorted.json src/zh-cht/locale/dim.json

      - name: Check for new files (DIM)
        id: porcelain
        run: echo ::set-output name=porcelain::"$(git status --porcelain)"

#      - name: Push changes (DIM)
#        if: steps.porcelain.outputs.porcelain
#        uses: delphiactual/github-push-action@master
#        with:
#          github_token: ${{ secrets.I18N_PAT }}
#          commit_message: "i18n"
#          user_email: "destinyitemmanager@gmail.com"
#          user_name: "DIM i18n Bot"
#          branch: master

      - name: Create Pull Request (DIM)
        if: steps.porcelain.outputs.porcelain
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: i18n - ${{ env.GITHUB_SHA_SHORT }}
          committer: DIM i18n Bot <destinyitemmanager@gmail.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: '[i18n] Updates'
          body: i18n updates
          labels: i18n, automated pr
          reviewers: delphiactual
          branch: i18n
