# This workflow runs when a PR is merged
# This workflow runs every Monday @ 0000 UTC (1700 PST)
name: Publish Release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout - DIM
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: '14.x'

      - name: Cache eslint
        uses: actions/cache@v2
        env:
          cache-name: cache-eslint
        with:
          path: ~/.cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/eslint.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: yarn install
        uses: bahmutov/npm-install@v1

      - name: yarn test
        run: yarn test

      - name: yarn run lint-check
        run: |
          find . -type d -name "node_modules" -prune -o -type f -iregex '.*.ts\|.*.js\|.*.tsx\|.*.jsx' -exec ./build/set-mtime-to-md5.sh {} \;
          yarn run lint-check

      - name: openssl
        run: openssl aes-256-cbc -K "$encrypted_472c4900477c_key" -iv "$encrypted_472c4900477c_iv" -in config/dim_travis.rsa.enc -out config/dim_travis.rsa -d && chmod 600 config/dim_travis.rsa
        env:
          encrypted_472c4900477c_key: ${{ secrets.encrypted_472c4900477c_key }}
          encrypted_472c4900477c_iv: ${{ secrets.encrypted_472c4900477c_iv }}

      - name: build release
        run: yarn run build-release
        env:
          WEB_API_KEY: ${{ secrets.WEB_API_KEY }}
          WEB_OAUTH_CLIENT_ID: ${{ secrets.WEB_OAUTH_CLIENT_ID }}
          WEB_OAUTH_CLIENT_SECRET: ${{ secrets.WEB_OAUTH_CLIENT_SECRET }}
          DIM_API_KEY: ${{ secrets.DIM_API_KEY }}

      - name: Set Version
        run: echo ::set-env name=VERSION::"$(node -p -e "require('./package.json').version)"

      - name: Echo Version
        run: echo New production version is $VERSION

      - name: Compress Files
        uses: stefh/ghaction-CompressFiles@v1
        with:
          path: '/dist'
          extensions: '.js,.html,.css,.json,.map,.ttf,.eot,.svg,.wasm'
          tools: 'brotli,gzip'

      - name: rsync content
        # Sync everything but the HTML first, so it's ready to go
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --exclude="*.html, service-worker.js, version.json"
          path: "dist/"
          remote_path: ${{ secrets.REMOTE_PATH }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_key: 'config/dim_travis.rsa'

      - name: rsync HTML
        # Then sync the HTML which will start using the new content
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --include="*.html, service-worker.js, version.json"
          path: "dist/"
          remote_path: ${{ secrets.REMOTE_PATH }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_key: 'config/dim_travis.rsa'

      - name: Update CF
        if: $CLOUDFLARE_KEY
        run: |
              curl -X POST "https://api.cloudflare.com/client/v4/zones/2c34c69276ed0f6eb2b9e1518fe56f74/purge_cache" \
              -H "X-Auth-Email: $CLOUDFLARE_EMAIL" \
              -H "X-Auth-Key: $CLOUDFLARE_KEY" \
              -H "Content-Type: application/json" \
              --data '{"files":["https://beta.destinyitemmanager.com", "https://beta.destinyitemmanager.com/index.html", "https://beta.destinyitemmanager.com/version.json", "https://beta.destinyitemmanager.com/service-worker.js", "https://beta.destinyitemmanager.com/gdrive-return.html", "https://beta.destinyitemmanager.com/return.html", "https://beta.destinyitemmanager.com/manifest-webapp-6-2018.json", "https://beta.destinyitemmanager.com/manifest-webapp-6-2018-ios.json"]}'
        env:
          CLOUDFLARE_KEY: ${{ secrets.CLOUDFLARE_KEY }},
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }},
